### ISSUE TITLE
Shifa Repertory Screen Added 

### ISSUE THREAD

**Issue by nasihere** [ShifaMicrotechSupport/shifa-online#8]
<img width="509" alt="screen shot 2016-03-25 at 1 05 13 pm" src="https://cloud.githubusercontent.com/assets/4184377/14052828/4818db3c-f28a-11e5-9b48-8c6a41aeb3ce.png">

**Comment by nasihere** [comment]
Please comment and let me knw your feedback

**Comment by nasihere** [comment]
<img width="1655" alt="screen shot 2016-03-25 at 1 09 09 pm" src="https://cloud.githubusercontent.com/assets/4184377/14052884/d73220c6-f28a-11e5-9c62-9bb47fc25a62.png">
<img width="1112" alt="screen shot 2016-03-25 at 1 09 27 pm" src="https://cloud.githubusercontent.com/assets/4184377/14052890/eb7b98c8-f28a-11e5-87bb-e545aeaa898f.png">

**Comment by nasihere** [comment]
<img width="1680" alt="screen shot 2016-03-25 at 5 19 10 pm" src="https://cloud.githubusercontent.com/assets/4184377/14056770/cc2554fa-f2ad-11e5-993e-ef0683ea5e12.png">
<img width="1680" alt="screen shot 2016-03-25 at 5 19 17 pm" src="https://cloud.githubusercontent.com/assets/4184377/14056773/cc2a1ab2-f2ad-11e5-939f-ef6703fa0136.png">
<img width="1680" alt="screen shot 2016-03-25 at 5 19 22 pm" src="https://cloud.githubusercontent.com/assets/4184377/14056771/cc271722-f2ad-11e5-9534-80fef6e83c53.png">
<img width="629" alt="screen shot 2016-03-25 at 5 19 31 pm" src="https://cloud.githubusercontent.com/assets/4184377/14056772/cc28f024-f2ad-11e5-9fcc-c420187b0608.png">

**Comment by nasihere** [comment]
<img width="1331" alt="screen shot 2016-03-25 at 5 57 02 pm" src="https://cloud.githubusercontent.com/assets/4184377/14057098/740d23d2-f2b3-11e5-9337-fff97cdee2d1.png">
<img width="1680" alt="screen shot 2016-03-25 at 5 59 56 pm" src="https://cloud.githubusercontent.com/assets/4184377/14057099/7425ab46-f2b3-11e5-920a-aaf14baf888f.png">

**Comment by nasihere** [comment]
<img width="659" alt="screen shot 2016-03-25 at 11 45 43 pm" src="https://cloud.githubusercontent.com/assets/4184377/14058626/c3246522-f2e3-11e5-86c1-438a5def88ca.png">

**Comment by nasihere** [comment]
<img width="1670" alt="screen shot 2016-03-26 at 10 21 28 am" src="https://cloud.githubusercontent.com/assets/4184377/14061402/9cb53228-f33c-11e5-916d-4c1e1f5ae08b.png">
<img width="844" alt="screen shot 2016-03-26 at 10 21 35 am" src="https://cloud.githubusercontent.com/assets/4184377/14061403/9cb7858c-f33c-11e5-98dc-5c920f375625.png">

**Comment by nasihere** [comment]
![Uploading Screen Shot 2016-03-26 at 11.07.17 AM.png…]()

**Comment by nasihere** [comment]
<img width="617" alt="screen shot 2016-03-26 at 11 07 17 am" src="https://cloud.githubusercontent.com/assets/4184377/14061745/59af4c94-f345-11e5-9906-5cef6497753b.png">
<img width="1388" alt="screen shot 2016-03-26 at 11 24 36 am" src="https://cloud.githubusercontent.com/assets/4184377/14061746/59af57ac-f345-11e5-873c-6279b0f298fe.png">

**Comment by nazimdadan** [comment]
Designs looks promising

**Comment by nasihere** [comment]
thanks nazim..

we need to handover prototype to other team member for api mapping.

**Comment by nasihere** [comment]
![Uploading Screen Shot 2016-03-29 at 7.40.07 PM.png…]()
